name: Lint code
on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linter:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: MegaLinter
        id: megalinter
        uses: oxsecurity/megalinter/flavors/go@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
